### ISSUE TITLE
Upgrade our Travis.yml for Node 8

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-respec-ci#21]
[à la respec](https://github.com/w3c/respec/blob/develop/.travis.yml) (but may or may not be possible wrt python dependencies)

incl upgrade to trusty?

**Comment by vivienlacourba** [comment]
Both done in https://github.com/w3c/webrtc-respec-ci/pull/25

Scripts now run on Travic trusty enviroment and we use Node LTS (same as respec).
